### ISSUE TITLE
Replace references to `commands` with `scaffolds`

### ISSUE THREAD

**Issue by foxleigh81** [spacenectar/builda#59]
`commands` is going to be a part of the `builda run` command (See #60), so existing references to `command` will need to be replaced. As they will only be for scaffolds, it makes sense to name them down as such.

**Comment by foxleigh81** [comment]
I am thinking of changing the `builda.json` file to look something like this:

```json
{
  "name": "Builda Website",
  "watched_folders": [
    "components",
    "pages",
    "styles"
  ],
  "prefabs": {
    "the-burrows": {
      "version": "1.0.0",
      "resolve": "github",
      "repository": "builda-modules/the-burrows",
      "root": "/"
    }
  },
  "scaffolds": {
    "arctic-fox": {
      "version": "1.0.0",
      "resolve": "github",
      "moduleUrl": "builda-modules/scaffold_arctic-fox"
    },
    "red-fox": {
      "version": "1.0.0",
      "resolve": "github",
      "moduleUrl": "builda-modules/scaffold_red-fox"
    }
  },
  "commands": {
    "run": {
      "dev": {
        "use": "the-burrows",
        "run": "next dev"
      }
    },
    "scaffold": {
      "atom": {
        "outputPath": "./components/atoms",
        "use": "component"
      },
      "molecule": {
        "outputPath": "./components/molecules",
        "use": "component"
      },
      "organism": {
        "outputPath": "./components/organisms",
        "use": "component"
      },
      "partial": {
        "outputPath": "./components/partials",
        "use": "component"
      },
      "page": {
        "outputPath": "./pages",
        "use": "page"
      }
    }
  }
}
```

This will do several things:

1. It will fulfil the requirements of this issue by splitting the `commands` section into two, a `commands.run` section and a `commands.scaffold` section.
2. It will add resolution paths for the scaffold and prefab modules, meaning that the .builda folder can safely be excluded from version control.
3. it adds a `watched_folders` section, which will allow for prefabs to be aware of which folders should be synchronized (this should be pre-populated when installing a prefab).
4. It removes the `modules` entry and replaces it with a `scaffolds` and a `prefabs` entry instead. The prefabs will also have a `root` property which will tell the application where the prefab should live in relation to the rest of the app (so sub-prefabs can be installed with ease).

**Comment by foxleigh81** [comment]
Another alternative is to use the TOML format. I'm currently undecided on how that will look or if it's the right choice. Here is an example of what that may look like:

```TOML
# A list of folders which will be under active development.
watched_folders = [
  "components",
  "pages",
  "styles"
]


# The prefabs to use in the project.
[[prefab]]
  name = "the-burrows"
  version = "1.0.0"
  resolve = "github"
  repository = "builda-modules/the-burrows"
  root = "/"

# The scaffolds to use in the project.

[[scaffold]]
  name = "arctic-fox"
  version = "1.0.0"
  resolve = "github"
  moduleUrl = "builda-modules/scaffold_arctic-fox"

[[scaffold]]
  name = "red-fox"
  version = "1.0.0"
  resolve = "github"
  moduleUrl = "builda-modules/scaffold_red-fox"

# The commands to run in the project

[[command]]
  type = "run"
  name = "dev"
  use = "the-burrows"
  run = "next dev"

[[command]]
  type = "scaffold"
  name = "atom"
  outputPath = "./components/atoms"
  use = "component"

[[command]]
  type = "scaffold"
  name = "molecule"
  outputPath = "./components/molecules"
  use = "component"

[[command]]
  type = "scaffold"
  name = "organism"
  outputPath = "./components/organisms"
  use = "component"
```
